name: Sql database update

on:
  push:
    branches:
      - sqldb
    paths:
    - 'readmefortesting.md' 
env:
  AZURE_SQL_SERVERNAME: vijaysqldbserver.database.windows.net 

jobs:
  azuresetup:
    
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.DEPLOYGITHUB }}

    - name: get sqlpackage version
      working-directory: C:\Program Files\Microsoft SQL Server\150\DAC\bin\
      run: ./sqlpackage.exe /version

    # Azure logout 
    - name: logout
      run: |
        az logout 
